<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KamarSeeder extends Seeder
{
    public function run()
    {
        // Clear existing data
        $this->db->table('kamar')->truncate();

        $data = [
            [
                'nomor_kamar' => 'A-101',
                'tipe_kamar'  => 'Single',
                'kapasitas'   => 1,
                'harga'       => '500000.00',
                'deskripsi'   => 'Kamar single nyaman dengan fasilitas dasar, cocok untuk mahasiswa.',
                'foto_kamar'  => 'kamar_a101.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'WiFi, Kasur, Lemari, Meja Belajar',
                'informasi_kamar' => 'Luas kamar 3x4 meter, ventilasi baik, pencahayaan cukup',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu sesama jenis kelamin',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'A-102',
                'tipe_kamar'  => 'Double',
                'kapasitas'   => 2,
                'harga'       => '800000.00',
                'deskripsi'   => 'Kamar double dengan AC dan kamar mandi dalam.',
                'foto_kamar'  => 'kamar_a102.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur, Lemari, Meja Belajar, Kamar Mandi Dalam',
                'informasi_kamar' => 'Luas kamar 4x5 meter, AC 1/2 PK, hot water shower',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'A-103',
                'tipe_kamar'  => 'Single',
                'kapasitas'   => 1,
                'harga'       => '550000.00',
                'deskripsi'   => 'Kamar single premium dengan balkon pribadi.',
                'foto_kamar'  => 'kamar_a103.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'WiFi, Kasur, Lemari, Meja Belajar, Balkon',
                'informasi_kamar' => 'Luas kamar 3x4 meter, balkon menghadap taman',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu sesama jenis kelamin',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'B-201',
                'tipe_kamar'  => 'Premium',
                'kapasitas'   => 1,
                'harga'       => '1500000.00',
                'deskripsi'   => 'Kamar premium lengkap fasilitas dengan dapur mini.',
                'foto_kamar'  => 'kamar_b201.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur, Lemari, Meja Belajar, Kamar Mandi Dalam, Dapur Mini, TV',
                'informasi_kamar' => 'Luas kamar 5x6 meter, AC 1 PK, smart TV 32 inch',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis, Dilarang memasak makanan berbau',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam, cleaning service 2x seminggu',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'B-202',
                'tipe_kamar'  => 'Double',
                'kapasitas'   => 2,
                'harga'       => '1000000.00',
                'deskripsi'   => 'Kamar double dengan fasilitas lengkap dan area kerja.',
                'foto_kamar'  => 'kamar_b202.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur, Lemari, Meja Belajar, Sofa, Kamar Mandi Dalam',
                'informasi_kamar' => 'Luas kamar 5x5 meter, AC 1 PK, area kerja terpisah',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'B-203',
                'tipe_kamar'  => 'Single',
                'kapasitas'   => 1,
                'harga'       => '700000.00',
                'deskripsi'   => 'Kamar single dengan pemandangan kota.',
                'foto_kamar'  => 'kamar_b203.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'WiFi, Kasur, Lemari, Meja Belajar, Jendela Besar',
                'informasi_kamar' => 'Luas kamar 3x4 meter, jendela besar menghadap kota',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu sesama jenis kelamin',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'C-301',
                'tipe_kamar'  => 'Triple',
                'kapasitas'   => 3,
                'harga'       => '1200000.00',
                'deskripsi'   => 'Kamar triple untuk 3 orang dengan ruang bersama.',
                'foto_kamar'  => 'kamar_c301.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur, Lemari, Meja Belajar, Ruang Tamu Kecil, Kamar Mandi Dalam',
                'informasi_kamar' => 'Luas kamar 6x7 meter, AC 1.5 PK, ruang tamu bersama',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis, Wajib rapi dan bersih',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam, cleaning service harian',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'C-302',
                'tipe_kamar'  => 'Double',
                'kapasitas'   => 2,
                'harga'       => '900000.00',
                'deskripsi'   => 'Kamar double dengan fasilitas modern.',
                'foto_kamar'  => 'kamar_c302.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur, Lemari, Meja Belajar, Kamar Mandi Dalam, Water Heater',
                'informasi_kamar' => 'Luas kamar 4x5 meter, AC 1 PK, water heater untuk mandi',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'C-303',
                'tipe_kamar'  => 'Single',
                'kapasitas'   => 1,
                'harga'       => '650000.00',
                'deskripsi'   => 'Kamar single ekonomis dengan fasilitas lengkap.',
                'foto_kamar'  => 'kamar_c303.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'WiFi, Kasur, Lemari, Meja Belajar, Kipas Angin',
                'informasi_kamar' => 'Luas kamar 3x4 meter, kipas angin besar',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu sesama jenis kelamin',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_kamar' => 'D-401',
                'tipe_kamar'  => 'VIP',
                'kapasitas'   => 1,
                'harga'       => '2000000.00',
                'deskripsi'   => 'Kamar VIP dengan fasilitas mewah dan pelayanan premium.',
                'foto_kamar'  => 'kamar_d401.jpg',
                'status'      => 'Tersedia',
                'fasilitas_fitur' => 'AC, WiFi, Kasur King Size, Lemari, Meja Kerja, Sofa, Kamar Mandi Dalam, Water Heater, TV, Mini Bar, Balkon',
                'informasi_kamar' => 'Luas kamar 6x6 meter, AC 1.5 PK, TV LED 42 inch, balkon pribadi',
                'aturan_kamar' => 'Dilarang merokok, Dilarang membawa tamu lawan jenis, Dilarang membuat keributan',
                'informasi_penting' => 'Listrik sudah termasuk, air bersih tersedia 24 jam, AC menyala 24 jam, cleaning service harian, room service 24 jam',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('kamar')->insertBatch($data);
    }
}
